version: 0.0
os: linux
files:
  - source: .  # Deploy everything from the root of your repository
    destination: /home/ubuntu/Travel-Planner
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root